In [ ]:
import numpy as np
import timeit

In [ ]:
list1 = list(range(1000))
list2 = list(range(1000))

In [ ]:
python_time = timeit.timeit(lambda: sum(x * y for x, y in zip(list1, list2)), number=10000)

In [ ]:
array1 = np.arange(1000)
array2 = np.arange(1000)

In [ ]:
numpy_time = timeit.timeit(lambda: np.dot(array1, array2), number = 10000)

In [ ]:
print(f"Python Time = {python_time}")
print(f"Numpy Time = {numpy_time}")

Python Time = 1.0578524730000254
Numpy Time = 0.028571052000074815


In [ ]:
print("python time is: ", python_time)

python time is:  1.0578524730000254


In [ ]:
my_array = np.array([1,2,3,4,5,6])

In [ ]:
my_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.array([1.2,1.5,2,3,4,7,5], dtype='int')

array([1, 1, 2, 3, 4, 7, 5])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
9 * np.ones((4,5))

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [ ]:
np.full((4,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.arange(4, 10, 2)

array([4, 6, 8])

In [ ]:
np.eye(4, 5, dtype='bool')

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [ ]:
np.linspace(10, 19, 19)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. ])

# **Random Numbers With NumPy**

In [ ]:
np.random.rand(2,3)

array([[0.71562558, 0.9708265 , 0.71965757],
       [0.19264821, 0.15645651, 0.14906806]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.45236127,  0.58313611, -1.27006082],
       [-0.98547084, -0.82388792,  1.52339466]])

In [ ]:
np.random.normal(20, 5, (4,5))

array([[22.14047513, 20.43765002, 23.97964805, 15.07472183, 19.60821228],
       [14.45150902, 27.20464247, 22.20204973, 17.42095239, 26.60448406],
       [20.68829384, 20.77323596, 19.56417065, 25.6936188 , 17.37742172],
       [19.08676489, 28.25777324, 16.47975629, 24.98098598, 21.20843798]])

In [ ]:
my_random_matrix = np.random.randint(0,100, (10,10))

In [ ]:
my_random_matrix.dtype

dtype('int64')

# **Reshaping with NumPy**

In [ ]:
vector = np.arange(15)

In [ ]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
vector.reshape(5,4)

ValueError: ignored

In [ ]:
new_vector = np.array([1, 5, -8, -3, 10, 6, -6, 24, 10, -8])

In [ ]:
new_vector.min()

-8

In [ ]:
new_vector.argmin()

2

In [ ]:
array1 = np.array(np.random.rand(2,3))
array2 = np.array(np.random.rand(2,3))

In [ ]:
array1

array([[0.83981244, 0.01202975, 0.14704605],
       [0.70134317, 0.04660636, 0.62246224]])

In [ ]:
array2

array([[0.65578757, 0.99980053, 0.81114808],
       [0.30797884, 0.995194  , 0.19469574]])

In [ ]:
np.concatenate([array1, array2], axis=1)

array([[0.83981244, 0.01202975, 0.14704605, 0.65578757, 0.99980053,
        0.81114808],
       [0.70134317, 0.04660636, 0.62246224, 0.30797884, 0.995194  ,
        0.19469574]])

In [ ]:
my_vector = np.arange(15)

In [ ]:
my_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.split(my_vector, 5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

In [ ]:
x

array([0, 1, 2, 3, 4])

In [ ]:
y

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
my_mat = np.arange(30).reshape(6,5)

In [ ]:
my_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.split(my_mat, [1, 5])

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]])]

In [ ]:
my_array = np.array([4,-2,3,0,-1,9,8,5,-6])

In [ ]:
my_array

array([ 4, -2,  3,  0, -1,  9,  8,  5, -6])

In [ ]:
np.sort(my_array, )

array([-6, -2, -1,  0,  3,  4,  5,  8,  9])

In [ ]:
my_mat = np.random.randint(0,10, (4,5))

In [ ]:
my_mat

array([[2, 8, 6, 0, 3],
       [5, 4, 6, 4, 0],
       [2, 7, 1, 3, 1],
       [0, 5, 2, 1, 4]])

In [ ]:
np.sort(my_mat.reshape(1,-1)).reshape(4,5)

array([[0, 0, 0, 1, 1],
       [1, 2, 2, 2, 3],
       [3, 4, 4, 4, 5],
       [5, 6, 6, 7, 8]])

In [ ]:
my_mat

array([[2, 8, 6, 0, 3],
       [5, 4, 6, 4, 0],
       [2, 7, 1, 3, 1],
       [0, 5, 2, 1, 4]])

In [ ]:
my_mat = np.arange(30).reshape(6,5)

In [ ]:
my_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.split(my_mat, [2, 3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [ ]:
my_vector = np.arange(15)

In [ ]:
my_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_vector[-3]

12

In [ ]:
my_mat = np.arange(30).reshape(6,5)

In [ ]:
my_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
my_mat[-1:] = 90

In [ ]:
my_mat

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10, 100,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 90,  90,  90,  90,  90]])

In [ ]:
my_array[(my_array < 0) & (my_array > -2)]

array([-1])

In [ ]:
my_vector = np.arange(15)

In [ ]:
my_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.log10(my_vector)

<ipython-input-151-390956fc727d>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(my_vector)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804])

In [ ]:
my_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_vector.mean()

7.0

In [ ]:
my_vector.sum()

105

In [ ]:
my_vector.median()

AttributeError: ignored

In [ ]:
my_vector.max()

14

In [ ]:
my_vector.std()

4.320493798938574

In [ ]:
my_vector.var()

18.666666666666668

# **Introduction to Pandas**

In [ ]:
import pandas as pd

# **Pandas Series**

In [ ]:
my_data = np.random.randint(0,10,10)
my_data

array([8, 6, 8, 5, 0, 3, 2, 0, 8, 8])

In [ ]:
my_index = "a b c d e f g h i j".split()
my_index

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
my_series = pd.Series(data = my_data, index=my_index)

In [ ]:
my_series

a    8
b    6
c    8
d    5
e    0
f    3
g    2
h    0
i    8
j    8
dtype: int64

In [ ]:
my_series.head()

a    8
b    6
c    8
d    5
e    0
dtype: int64

In [ ]:
my_series = my_series.sort_values()

In [ ]:
my_series.sort_index()

a    8
b    6
c    8
d    5
e    0
f    3
g    2
h    0
i    8
j    8
dtype: int64

In [ ]:
my_series.isin([8])

e    False
h    False
g    False
f    False
d    False
b    False
a     True
c     True
i     True
j     True
dtype: bool

In [ ]:
my_series.values

array([0, 0, 2, 3, 5, 6, 8, 8, 8, 8])

In [ ]:
my_series.index

Index(['e', 'h', 'g', 'f', 'd', 'b', 'a', 'c', 'i', 'j'], dtype='object')

In [ ]:
my_series["j"]

8

# **DataFrame**

In [ ]:
my_data = np.arange(48).reshape(8,6)
my_index = "a b c d e f g h".split()
my_cols = "Col1 Col2 Col3 Col4 Col5 Col6".split()

In [ ]:
df = pd.DataFrame(data=my_data , index=my_index , columns=my_cols)
df

Col1  Col2  Col3  Col4  Col5  Col6
a     0     1     2     3     4     5
b     6     7     8     9    10    11
c    12    13    14    15    16    17
d    18    19    20    21    22    23
e    24    25    26    27    28    29
f    30    31    32    33    34    35
g    36    37    38    39    40    41
h    42    43    44    45    46    47

In [ ]:
df.head(3)

Col1  Col2  Col3  Col4  Col5  Col6
a     0     1     2     3     4     5
b     6     7     8     9    10    11
c    12    13    14    15    16    17

In [ ]:
df.tail()

Col1  Col2  Col3  Col4  Col5  Col6
d    18    19    20    21    22    23
e    24    25    26    27    28    29
f    30    31    32    33    34    35
g    36    37    38    39    40    41
h    42    43    44    45    46    47

In [ ]:
df.columns

Index(['Col1', 'Col2', 'Col3', 'Col4', 'Col5', 'Col6'], dtype='object')

In [ ]:
df.values

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [ ]:
df.shape

(8, 6)

In [ ]:
df.ndim

2

In [ ]:
df.size

48

In [ ]:
df

Col1  Col2  Col3  Col4  Col5  Col6
a     0     1     2     3     4     5
b     6     7     8     9    10    11
c    12    13    14    15    16    17
d    18    19    20    21    22    23
e    24    25    26    27    28    29
f    30    31    32    33    34    35
g    36    37    38    39    40    41
h    42    43    44    45    46    47

In [ ]:
df["e":"g"]["Col1"]

e    24
f    30
g    36
Name: Col1, dtype: int64

In [ ]:
df

Col1  Col2  Col3  Col4  Col5  Col6
a     0     1     2     3     4     5
b     6     7     8     9    10    11
c    12    13    14    15    16    17
d    18    19    20    21    22    23
e    24    25    26    27    28    29
f    30    31    32    33    34    35
g    36    37    38    39    40    41
h    42    43    44    45    46    47

In [ ]:
df > 30

Col1   Col2   Col3   Col4   Col5   Col6
a  False  False  False  False  False  False
b  False  False  False  False  False  False
c  False  False  False  False  False  False
d  False  False  False  False  False  False
e  False  False  False  False  False  False
f  False   True   True   True   True   True
g   True   True   True   True   True   True
h   True   True   True   True   True   True

In [ ]:
my_data = np.random.randint(0,20,48).reshape(8,6)
my_index = "a b c d e f g h".split()
my_cols = "Col1 Col2 Col3 Col4 Col5 Col6".split()
df = pd.DataFrame(data=my_data , index=my_index , columns=my_cols)
df

Col1  Col2  Col3  Col4  Col5  Col6
a    14     3    15    19    11     2
b    12    14    14    17     8     0
c    14     8     9     4    16    12
d    18     6    17    17    15    13
e    17    15     9     2    12     8
f    16    10    16    17    13    19
g    10    10    10    19    18     9
h     6     7     3    17    10    14

In [ ]:
df[df > 1]

Col1  Col2  Col3  Col4  Col5  Col6
a    14     3    15    19    11   2.0
b    12    14    14    17     8   NaN
c    14     8     9     4    16  12.0
d    18     6    17    17    15  13.0
e    17    15     9     2    12   8.0
f    16    10    16    17    13  19.0
g    10    10    10    19    18   9.0
h     6     7     3    17    10  14.0